package com.alaskalany.android.model

data class DailyData(
    val time: Int = 0,
    val summary: String = "",
    val icon: String = "",
    val sunriseTime: Int = 0,
    val sunsetTime: Int = 0,
    val moonPhase: Double = 0.0,
    val precipIntensity: Double = 0.0,
    val precipIntensityMax: Double = 0.0,
    val precipIntensityMaxTime: Int = 0,
    val precipProbability: Double = 0.0,
    val precipType: String = "",
    val temperatureHigh: Double = 0.0,
    val temperatureHighTime: Int = 0,
    val temperatureLow: Double = 0.0,
    val temperatureLowTime: Int = 0,
    val apparentTemperatureHigh: Double = 0.0,
    val apparentTemperatureHighTime: Int = 0,
    val apparentTemperatureLow: Double = 0.0,
    val apparentTemperatureLowTime: Int = 0,
    val dewPoint: Double = 0.0,
    val humidity: Double = 0.0,
    val pressure: Double = 0.0,
    val windSpeed: Double = 0.0,
    val windGust: Double = 0.0,
    val windGustTime: Int = 0,
    val windBearing: Int = 0,
    val cloudCover: Double = 0.0,
    val uvIndex: Int = 0,
    val uvIndexTime: Int = 0,
    val visibility: Double = 0.0,
    val ozone: Int = 0,
    val temperatureMin: Double = 0.0,
    val temperatureMinTime: Int = 0,
    val temperatureMax: Double = 0.0,
    val temperatureMaxTime: Int = 0,
    val apparentTemperatureMin: Double = 0.0,
    val apparentTemperatureMinTime: Int = 0,
    val apparentTemperatureMax: Double = 0.0,
    val apparentTemperatureMaxTime: Int = 0
)