package com.alaskalany.android.model

interface IDailyData {
    val time: Double?
    val summary: String?
    val icon: String?
    val sunriseTime: Double?
    val sunsetTime: Double?
    val moonPhase: Double?
    val precipIntensity: Double?
    val precipIntensityMax: Double?
    val precipIntensityMaxTime: Double?
    val precipProbability: Double?
    val precipType: String?
    val temperatureHigh: Double?
    val temperatureHighTime: Double?
    val temperatureLow: Double?
    val temperatureLowTime: Double?
    val apparentTemperatureHigh: Double?
    val apparentTemperatureHighTime: Double?
    val apparentTemperatureLow: Double?
    val apparentTemperatureLowTime: Double?
    val dewPoint: Double?
    val humidity: Double?
    val pressure: Double?
    val windSpeed: Double?
    val windGust: Double?
    val windGustTime: Double?
    val windBearing: Double?
    val cloudCover: Double?
    val uvIndex: Double?
    val uvIndexTime: Double?
    val visibility: Double?
    val ozone: Double?
    val temperatureMin: Double?
    val temperatureMinTime: Double?
    val temperatureMax: Double?
    val temperatureMaxTime: Double?
    val apparentTemperatureMin: Double?
    val apparentTemperatureMinTime: Double?
    val apparentTemperatureMax: Double?
    val apparentTemperatureMaxTime: Double?
}